local harpoon = require("harpoon")
local Remap = require("keymap")
local n = Remap.nnoremap

harpoon:setup()

n("<leader>ha", function()
	harpoon:list():add()
end)
n("<leader>hl", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)
n("<F1>", function()
	harpoon:list():select(1)
end)
n("<F2>", function()
	harpoon:list():select(2)
end)
n("<F3>", function()
	harpoon:list():select(3)
end)
n("<F4>", function()
	harpoon:list():select(4)
end)
n("<F5>", function()
	harpoon:list():select(5)
end)
